# -*- coding: utf-8 -*-
"""Vision_por_computadora_TP_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7pnHS_Pp9afyF4WcId-9c1EICoagRTw

**TP1**

Parte 1 (imágenes en /white_patch):

Implementar el algoritmo White Patch para librarnos de las diferencias de color de iluminación.

Mostrar los resultados obtenidos y analizar las posibles fallas (si es que las hay) en el caso de White patch.

Parte 2:

Para las imágenes img1_tp.png y img2_tp.png leerlas con OpenCV en escala de grises y visualizarlas.

Elija el número de bins que crea conveniente y grafique su histograma, compare los histogramas entre sí. Explicar lo que se observa, si tuviera que entrenar un modelo de clasificación/detección de imágenes, ¿considera que puede ser de utilidad tomar como features a los histogramas?
"""

# ===== LIBRERÍAS =====
import cv2
import numpy as np
import os
import matplotlib.pyplot as plt

# ===== ALGORITMO WHITE PATCH =====
def white_patch_algorithm(img):
    img = img.astype(np.float32)
    max_vals = np.max(img, axis=(0, 1))  # máximo de cada canal
    for c in range(3):
        if max_vals[c] > 0:
            img[:, :, c] = img[:, :, c] / max_vals[c] * 255
    return np.clip(img, 0, 255).astype(np.uint8)

# ===== RUTA DE LA CARPETA =====
carpeta = "white_patch"

# ===== PROCESAR TODAS LAS IMÁGENES =====
for archivo in os.listdir(carpeta):
    if archivo.lower().endswith((".png", ".jpg", ".jpeg")):
        path_in = os.path.join(carpeta, archivo)

        # Leer imagen
        img = cv2.imread(path_in)
        if img is None:
            print(f"⚠️ No se pudo leer: {archivo}")
            continue

        # Aplicar algoritmo
        img_wp = white_patch_algorithm(img)

        # Guardar resultado
        nombre, ext = os.path.splitext(archivo)
        path_out = os.path.join(carpeta, f"{nombre}_wp{ext}")
        cv2.imwrite(path_out, img_wp)

        # Mostrar original y corregida
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img_wp_rgb = cv2.cvtColor(img_wp, cv2.COLOR_BGR2RGB)

        plt.figure(figsize=(8,4))
        plt.subplot(1,2,1)
        plt.imshow(img_rgb)
        plt.title(f"Original: {archivo}")
        plt.axis("off")

        plt.subplot(1,2,2)
        plt.imshow(img_wp_rgb)
        plt.title("White Patch")
        plt.axis("off")
        plt.show()

        print(f"✅ Procesada {archivo} -> {nombre}_wp{ext}")

# ===== PARTE 2: HISTOGRAMAS =====
img1_path = "white_patch/img1_tp.png"
img2_path = "white_patch/img2_tp.png"

img1 = cv2.imread(img1_path, cv2.IMREAD_GRAYSCALE)
img2 = cv2.imread(img2_path, cv2.IMREAD_GRAYSCALE)

if img1 is None or img2 is None:
    print("⚠️ No se encontraron img1_tp.png y/o img2_tp.png, revisá las rutas.")
else:
    # Mostrar imágenes
    plt.figure(figsize=(10,4))
    plt.subplot(1,2,1)
    plt.imshow(img1, cmap="gray")
    plt.title("Imagen 1")
    plt.axis("off")

    plt.subplot(1,2,2)
    plt.imshow(img2, cmap="gray")
    plt.title("Imagen 2")
    plt.axis("off")
    plt.show()

    # Calcular histogramas
    bins = 32
    hist1 = cv2.calcHist([img1], [0], None, [bins], [0, 256])
    hist2 = cv2.calcHist([img2], [0], None, [bins], [0, 256])

    # Graficar histogramas (con ravel() y colores explícitos)
    plt.figure(figsize=(8,4))
    plt.plot(hist1.ravel(), color='blue', label="Hist Img1")
    plt.plot(hist2.ravel(), color='orange', label="Hist Img2")
    plt.title("Comparación de histogramas")
    plt.xlabel("Bins")
    plt.ylabel("Frecuencia")
    plt.legend()
    plt.show()


# ===== PARTE 2: HISTOGRAMAS =====
# Ajustá la ruta donde tengas estas imágenes
img1_path = "white_patch/img1_tp.png"
img2_path = "white_patch/img2_tp.png"

img1 = cv2.imread(img1_path, cv2.IMREAD_GRAYSCALE)
img2 = cv2.imread(img2_path, cv2.IMREAD_GRAYSCALE)

if img1 is None or img2 is None:
    print("⚠️ No se encontraron img1_tp.png y/o img2_tp.png, revisá las rutas.")
else:
    # Mostrar imágenes
    plt.figure(figsize=(10,4))
    plt.subplot(1,2,1)
    plt.imshow(img1, cmap="gray")
    plt.title("Imagen 1")
    plt.axis("off")

    plt.subplot(1,2,2)
    plt.imshow(img2, cmap="gray")
    plt.title("Imagen 2")
    plt.axis("off")
    plt.show()

    # Calcular histogramas
    bins = 256
    hist1 = cv2.calcHist([img1], [0], None, [bins], [0, 256]).flatten()
    hist2 = cv2.calcHist([img2], [0], None, [bins], [0, 256]).flatten()

    x = np.arange(bins)

    plt.figure(figsize=(10,5))
    plt.plot(x, hist1, color='blue', label="Hist Img1")
    plt.plot(x, hist2, color='orange', label="Hist Img2")
    plt.title("Comparación de histogramas")
    plt.xlabel("Nivel de gris (0-255)")
    plt.ylabel("Frecuencia")
    plt.legend()
    plt.show()

"""# Explicación del Código: White Patch + Histogramas

## Parte 1: Algoritmo White Patch

### Librerías usadas
- `cv2` → OpenCV, para procesamiento de imágenes: leer, modificar y guardar imágenes.  
- `numpy` → manejar arreglos y operaciones matemáticas sobre las matrices de píxeles.  
- `os` → listar archivos de carpetas y construir rutas.  
- `matplotlib.pyplot` → mostrar imágenes y gráficos dentro de Colab.

### Función `white_patch_algorithm(img)`
**Objetivo:** corregir el balance de blancos usando el principio de que el píxel más brillante debería ser blanco.  

**Paso a paso:**
1. `img.astype(np.float32)` → convierte la imagen a flotante para operaciones precisas.  
2. `np.max(img, axis=(0,1))` → encuentra el valor máximo de cada canal de color (B, G, R).  
3. Para cada canal:
   - Dividir todos los píxeles por el valor máximo.  
   - Multiplicar por 255 para escalar el canal.  
4. `np.clip(img, 0, 255)` → asegura que los valores queden en el rango válido.  
5. `astype(np.uint8)` → vuelve la imagen a enteros para poder guardarla como PNG/JPG.  

💡 **Idea clave:** elimina dominantes de color; por ejemplo, si la imagen está azulada, el azul se normaliza y los otros canales se ajustan proporcionalmente.

### Procesar todas las imágenes de una carpeta
- `os.listdir(carpeta)` → obtiene todos los archivos de la carpeta.  
- `archivo.lower().endswith(...)` → filtra solo imágenes.  
- `cv2.imread(path_in)` → carga la imagen en BGR.  
- `cv2.imwrite(path_out, img_wp)` → guarda la imagen procesada con `_wp` agregado al nombre.  

Para mostrar la original y la corregida:
- `cv2.cvtColor(img, cv2.COLOR_BGR2RGB)` → convierte BGR a RGB para matplotlib.  
- `plt.subplot` → permite mostrar ambas imágenes lado a lado.  
- `plt.axis("off")` → oculta los ejes, mostrando solo las imágenes.

---
## Parte 2: Histogramas

### Cargar imágenes en escala de grises
- `cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)` → convierte automáticamente la imagen a gris.  
- Permite calcular histogramas de intensidad más fácilmente.  
- Si la imagen no existe, se muestra un mensaje de advertencia.

### Mostrar imágenes
- `plt.imshow(img, cmap="gray")` → muestra la imagen en escala de grises.  
- `plt.subplot` → permite comparar varias imágenes lado a lado.

### Calcular histogramas
- `cv2.calcHist([img], [0], None, [bins], [0, 256])` → calcula la frecuencia de píxeles por rango de gris.  
- `[0]` → canal único porque la imagen es gris.  
- `bins` → número de divisiones del rango 0-255.  
- El histograma indica cuántos píxeles caen en cada rango de intensidad.

### Graficar histogramas
- `plt.plot(hist.ravel())` → grafica la frecuencia de píxeles por bin.  
- `.ravel()` → convierte el histograma a 1D, evitando problemas de visualización en matplotlib.  
- Colores explícitos (`blue` y `orange`) permiten diferenciar las imágenes.  
- Permite comparar visualmente el brillo y contraste de dos imágenes.

---

## Resumen conceptual
- **White Patch:** corrige la dominante de color ajustando el píxel más brillante a blanco.  
- **Histogramas:** muestran la distribución de niveles de gris, útil para analizar brillo y contraste entre imágenes.





"""